import Track from '#models/track'
import { BaseSeeder } from '@adonisjs/lucid/seeders'

export default class extends BaseSeeder {
  async run() {
    const france = await Track.findByOrFail('slug', 'france')
    const espagne = await Track.findByOrFail('slug', 'espagne')
    const italie = await Track.findByOrFail('slug', 'italie')
    const amerique = await Track.findByOrFail('slug', 'amerique')
    const allemagne = await Track.findByOrFail('slug', 'allemagne')
    const portugal = await Track.findByOrFail('slug', 'portugal')
    const qatar = await Track.findByOrFail('slug', 'qatar')
    const malaisie = await Track.findByOrFail('slug', 'malaisie')
    const paysBas = await Track.findByOrFail('slug', 'pays-bas')
    const angleterre = await Track.findByOrFail('slug', 'angleterre')
    const autriche = await Track.findByOrFail('slug', 'autriche')
    const indonesie = await Track.findByOrFail('slug', 'indonesie')
    const japon = await Track.findByOrFail('slug', 'japon')
    const australie = await Track.findByOrFail('slug', 'australie')
    const thailande = await Track.findByOrFail('slug', 'thailande')
    // Write your database queries inside the run method
    await Track.createMany([
      {
        name: 'Nogaro',
        slug: 'nogaro',
        countryId: france.id,
        city: 'Nogaro',
        address: "Av. de l'Autodrome, 32110 Nogaro, France",
        length: 3636,
        turns: '14 (5 à gauche et 9 à droite)',
        bestLapTime: '1.20.160',
        bestLapTimePilot: 'Alessandro Zanardi',
        width: 9.5,
        maxDb: 102,
        description: '6600 m2 de bâtiments couverts',
      },
      {
        name: 'Pau Arnos',
        slug: 'pau-arnos',
        countryId: france.id,
        city: 'Arnos',
        address: 'Circuit Arnos, Petrou, 64370 Arnos, France',
        length: 3030,
        turns: '12 (7 à droite et 5 à gauche)',
        bestLapTime: '1.10.870',
        bestLapTimePilot: 'Giedo Van der Garde',
        width: '9 a 12',
        maxDb: 102,
        description:
          '1 tracé principal de 3 030 mètres (5 tracés dérivés de 3 030 mètres & 600 mètres), circuit de karting',
      },
      {
        name: 'Navarra',
        slug: 'navarra',
        countryId: espagne.id,
        city: 'Los Arcos',
        address: 'Calle Malvasia 5, 31210 Los Arcos Spain',
        turns: '15 (7 à droite et 5 à gauche)',
        length: 3933,
        bestLapTime: '1.38.417',
        bestLapTimePilot: 'Cauvin Dominique',
        width: '9 a 12',
        maxDb: 102,
        description: 'Restaurant sur place, circuit de karting',
      },
      {
        name: 'Motorland Aràgon',
        slug: 'motorland-aragon',
        countryId: espagne.id,
        city: 'Alcañiz',
        address: 'Crta, A-2404, km 1, 44600 Alcaniz Spain',
        turns: '17 (7 à droite et 10 à gauche)',
        length: 5078,
        bestLapTime: '1.38.976',
        bestLapTimePilot: 'Raffaele Marciello',
        width: 15,
        maxDb: 102,
        description: 'Restaurant sur place, circuit de karting',
      },
      {
        name: 'Alcarras',
        slug: 'alcarras',
        countryId: espagne.id,
        city: 'Alcarras',
        address: 'km, Av. de Valmanya, 13, 25180 Alcarràs, Lleida, Spain',
        turns: '14 (10 à gauche, 4 à droite)',
        length: 3743,
        width: '14 a 15',
        maxDb: 102,
        description: 'Circuit de karting (1km17, 13 virages 8 à gauche, 5 à droite)',
      },
      {
        name: 'Jerez',
        slug: 'jerez',
        countryId: espagne.id,
        city: 'Jerez',
        address:
          'Carretera de Arcos-Jerez de la Frontera, Km 10, 11405 Jerez de la Frontera, Cádiz, Espagne',
        turns: '13 (5 à gauche, 8 à droite)',
        length: 4428,
        bestLapTime: '1.15.650',
        bestLapTimePilot: 'Michael Schumacher',
        width: '14 a 15',
      },
      {
        name: 'Calafat',
        slug: 'calafat',
        countryId: espagne.id,
        city: 'Calafat',
        address: 'Urb. Calafat, Circuit, 43860 Calafat, Tarragona, Espagne',
        turns: '19',
        length: 3250,
        width: '14 a 15',
      },
      {
        name: 'Dijon',
        slug: 'dijon',
        countryId: france.id,
        city: 'Dijon',
        address: '',
        turns: '16 (6 à gauche, 10 à droite)',
        length: 5250,
        width: 14,
      },
      {
        name: 'Misano',
        slug: 'misano',
        countryId: italie.id,
        city: 'Misano',
        address: '',
        turns: '16 (6 à gauche, 10 à droite)',
        length: 4230,
        width: 12,
      },
      {
        name: 'Autodromo Internazionale del Mugello',
        slug: 'autodromo-internazionale-del-mugello',
        countryId: italie.id,
        city: 'Mugello',
        address: '',
        turns: '15 (6 à gauche, 9 à droite)',
        length: 5250,
        width: 14,
      },
      {
        name: 'Magny Cours',
        slug: 'magny-cours',
        countryId: france.id,
        city: 'Magny Cours',
        address: '',
        turns: '16 (6 à gauche, 10 à droite)',
        length: 5250,
        width: 14,
      },
      {
        name: 'Ales',
        slug: 'ales',
        countryId: france.id,
        city: 'Ales',
        address: '',
        turns: '15 (6 à gauche, 9 à droite)',
        length: 4250,
        width: 12,
      },
      {
        name: 'Lusail International Circuit',
        slug: 'lusail-international-circuit',
        countryId: qatar.id,
        city: '',
        address: '',
        turns: '16 (6 à gauche, 10 à droite)',
        length: 5380,
        width: 12,
      },
      {
        name: 'Portimão - Autódromo Internacional do Algarve',
        slug: 'portimao-autodromo-internacional-do-algarve',
        countryId: portugal.id,
        city: '',
        address: '',
        turns: '15 (6 à gauche, 9 à droite)',
        length: 4590,
        width: 18,
      },
      {
        name: 'Circuit Of The Americas',
        slug: 'circuit-of-the-americas',
        countryId: amerique.id,
        city: '',
        address: '',
        turns: '20 (11 à gauche, 9 à droite)',
        length: 5510,
        width: 15,
      },
      {
        name: 'Circuito de Jerez - Ángel Nieto',
        slug: 'circuito-de-jerez-angel-nieto',
        countryId: espagne.id,
        city: 'Jerez',
        address: '',
        turns: '13 (5 à gauche, 8 à droite)',
        length: 4620,
        width: 11,
      },
      {
        name: 'Le Mans',
        slug: 'le-mans',
        countryId: france.id,
        city: 'Le Mans',
        address: '',
        turns: '14 (5 à gauche, 9 à droite)',
        length: 4190,
        width: 13,
      },
      {
        name: 'Circuit de Barcelona-Catalunya',
        slug: 'circuit-de-barcelona-catalunya',
        countryId: espagne.id,
        city: 'Barcelona',
        address: '',
        turns: '14 (6 à gauche, 8 à droite)',
        length: 4660,
        width: 12,
      },
      {
        name: 'TT Circuit Assen',
        slug: 'tt-circuit-assen',
        countryId: paysBas.id,
        city: 'Assen',
        address: '',
        turns: '18 (6 à gauche, 12 à droite)',
        length: 4542,
        width: 14,
      },
      {
        name: 'Sachsenring',
        slug: 'sachsenring',
        countryId: allemagne.id,
        city: 'Hohenstein-Ernstthal',
        address: '',
        turns: '13 (10 à gauche, 3 à droite)',
        length: 3671,
        width: 12,
      },
      {
        name: 'Silverstone Circuit',
        slug: 'silverstone-circuit',
        countryId: angleterre.id,
        city: 'Silverstone',
        address: '',
        turns: '18 (8 à gauche, 10 à droite)',
        length: 5891,
        width: 15,
      },
      {
        name: 'Red Bull Ring',
        slug: 'red-bull-ring',
        countryId: autriche.id,
        city: 'Spielberg',
        address: '',
        turns: '11 (3 à gauche, 8 à droite)',
        length: 4350,
        width: 12,
      },
      {
        name: 'Mandalika International Street Circuit',
        slug: 'mandalika-international-street-circuit',
        countryId: indonesie.id,
        city: 'Kuta Mandalika',
        address: '',
        turns: '17 (6 à gauche, 11 à droite)',
        length: 4300,
        width: 15,
      },
      {
        name: 'Motegi Twin Ring',
        slug: 'motegi-twin-ring',
        countryId: japon.id,
        city: 'Motegi',
        address: '',
        turns: '14 (6 à gauche, 8 à droite)',
        length: 4801,
        width: 15,
      },
      {
        name: 'Phillip Island',
        slug: 'phillip-island',
        countryId: australie.id,
        city: 'Phillip Island',
        address: '',
        turns: '12 (5 à gauche, 7 à droite)',
        length: 4445,
        width: 13,
      },
      {
        name: 'Chang International Circuit',
        slug: 'chang-international-circuit',
        countryId: thailande.id,
        city: 'Buriram',
        address: '',
        turns: '12 (5 à gauche, 7 à droite)',
        length: 4554,
        width: 12,
      },
      {
        name: 'Petronas Sepang International Circuit',
        slug: 'petronas-sepang-international-circuit',
        countryId: malaisie.id,
        city: 'Sepang',
        address: '',
        turns: '15 (5 à gauche, 10 à droite)',
        length: 5543,
        width: 16,
      },
      {
        name: 'Circuit Ricardo Tormo',
        slug: 'circuit-ricardo-tormo',
        countryId: espagne.id,
        city: 'Valencia',
        address: 'Salida, Autovía del Este, 334, 46380 Cheste, Valencia, Espagne',
        turns: '14 (9 à gauche, 5 à droite)',
        length: 4005,
        width: 12,
        maxDb: 118,
        bestLapTime: '1:29.401',
      },
    ])
  }
}
