/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AdminUsers: () => import('#controllers/admin_users_controller'),
  Auth: () => import('#controllers/auth_controller'),
  Countries: () => import('#controllers/countries_controller'),
  Mailer: () => import('#controllers/mailer_controller'),
  Maintenances: () => import('#controllers/maintenances_controller'),
  TrackDays: () => import('#controllers/track_days_controller'),
  Tracks: () => import('#controllers/tracks_controller'),
  User: () => import('#controllers/user_controller'),
  UserVehicles: () => import('#controllers/user_vehicles_controller'),
}
