/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt', 'uuid'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare uuid: string | null
}

export class CountrySchema extends BaseModel {
  static $columns = ['capital', 'createdAt', 'id', 'iso', 'name', 'slug', 'timezone', 'updatedAt', 'uuid'] as const
  $columns = CountrySchema.$columns
  @column()
  declare capital: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare iso: string
  @column()
  declare name: string
  @column()
  declare slug: string
  @column()
  declare timezone: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare uuid: string | null
}

export class MaintenanceSchema extends BaseModel {
  static $columns = ['cost', 'createdAt', 'date', 'details', 'id', 'mileage', 'name', 'nextMaintenanceMileage', 'type', 'updatedAt', 'userId', 'userVehicleId', 'uuid', 'workshop'] as const
  $columns = MaintenanceSchema.$columns
  @column()
  declare cost: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.date()
  declare date: DateTime
  @column()
  declare details: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare mileage: number | null
  @column()
  declare name: string
  @column()
  declare nextMaintenanceMileage: number | null
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number | null
  @column()
  declare userVehicleId: number | null
  @column()
  declare uuid: string | null
  @column()
  declare workshop: string | null
}

export class RateLimitSchema extends BaseModel {
  static $columns = ['expire', 'key', 'points'] as const
  $columns = RateLimitSchema.$columns
  @column()
  declare expire: bigint | number | null
  @column({ isPrimary: true })
  declare key: string
  @column()
  declare points: number
}

export class SubscriptionSchema extends BaseModel {
  static $columns = ['autoRenew', 'billingCycle', 'canceledAt', 'createdAt', 'endDate', 'features', 'id', 'plan', 'price', 'startDate', 'status', 'trialEndsAt', 'updatedAt', 'userId', 'uuid'] as const
  $columns = SubscriptionSchema.$columns
  @column()
  declare autoRenew: boolean
  @column()
  declare billingCycle: string
  @column.date()
  declare canceledAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.date()
  declare endDate: DateTime
  @column()
  declare features: any
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare plan: string
  @column()
  declare price: string
  @column.date()
  declare startDate: DateTime
  @column()
  declare status: string
  @column.date()
  declare trialEndsAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
  @column()
  declare uuid: string | null
}

export class TrackDaySchema extends BaseModel {
  static $columns = ['airTemperature', 'bestLapTime', 'chronos', 'createdAt', 'date', 'id', 'notes', 'totalDistance', 'totalLaps', 'trackCondition', 'trackId', 'trackTemperature', 'updatedAt', 'userId', 'userVehicleId', 'uuid', 'weather'] as const
  $columns = TrackDaySchema.$columns
  @column()
  declare airTemperature: number | null
  @column()
  declare bestLapTime: string | null
  @column()
  declare chronos: any | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.date()
  declare date: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare notes: string | null
  @column()
  declare totalDistance: string | null
  @column()
  declare totalLaps: number | null
  @column()
  declare trackCondition: string | null
  @column()
  declare trackId: number | null
  @column()
  declare trackTemperature: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number | null
  @column()
  declare userVehicleId: number | null
  @column()
  declare uuid: string | null
  @column()
  declare weather: string | null
}

export class TrackSchema extends BaseModel {
  static $columns = ['address', 'bestLapTime', 'bestLapTimePilot', 'city', 'countryId', 'createdAt', 'description', 'id', 'length', 'logoUrl', 'maxDb', 'name', 'slug', 'trackLayoutUrl', 'turns', 'updatedAt', 'uuid', 'width'] as const
  $columns = TrackSchema.$columns
  @column()
  declare address: string | null
  @column()
  declare bestLapTime: string | null
  @column()
  declare bestLapTimePilot: string | null
  @column()
  declare city: string
  @column()
  declare countryId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare length: string
  @column()
  declare logoUrl: string | null
  @column()
  declare maxDb: number | null
  @column()
  declare name: string
  @column()
  declare slug: string
  @column()
  declare trackLayoutUrl: string | null
  @column()
  declare turns: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare uuid: string | null
  @column()
  declare width: string | null
}

export class UserVehicleSchema extends BaseModel {
  static $columns = ['brand', 'createdAt', 'details', 'id', 'licensePlate', 'model', 'name', 'slug', 'type', 'updatedAt', 'userId', 'uuid', 'year'] as const
  $columns = UserVehicleSchema.$columns
  @column()
  declare brand: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare details: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare licensePlate: string | null
  @column()
  declare model: string | null
  @column()
  declare name: string
  @column()
  declare slug: string
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number | null
  @column()
  declare uuid: string | null
  @column()
  declare year: number | null
}

export class UserSchema extends BaseModel {
  static $columns = ['countryId', 'createdAt', 'email', 'firstName', 'id', 'lastName', 'password', 'preferences', 'role', 'updatedAt', 'uuid'] as const
  $columns = UserSchema.$columns
  @column()
  declare countryId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare firstName: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare lastName: string
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare preferences: any | null
  @column()
  declare role: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare uuid: string | null
}
